name: Blob storage website CI

on:
    push:
        branches: [ cn-api5 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name chocobo --auth-mode key -d 'cn-api5' -s .

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()